// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attribution.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

//#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
//#else
// #import "GPBProtocolBuffers.h"
//#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AttributionRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AttributionRoot : GPBRootObject
@end

#pragma mark - GetAttributionRequest

typedef GPB_ENUM(GetAttributionRequest_FieldNumber) {
  GetAttributionRequest_FieldNumber_AppId = 1,
  GetAttributionRequest_FieldNumber_AdvertiserId = 2,
  GetAttributionRequest_FieldNumber_AppUserId = 3,
  GetAttributionRequest_FieldNumber_AttributionSource = 4,
  GetAttributionRequest_FieldNumber_Data_p = 5,
  GetAttributionRequest_FieldNumber_NetworkUserId = 6,
  GetAttributionRequest_FieldNumber_Os = 7,
  GetAttributionRequest_FieldNumber_OsVersion = 8,
  GetAttributionRequest_FieldNumber_PackageName = 9,
  GetAttributionRequest_FieldNumber_PackageVersion = 10,
  GetAttributionRequest_FieldNumber_DeviceModel = 11,
  GetAttributionRequest_FieldNumber_Locale = 12,
  GetAttributionRequest_FieldNumber_TimeZoneAbv = 13,
  GetAttributionRequest_FieldNumber_TimeZone = 14,
  GetAttributionRequest_FieldNumber_Carrier = 15,
  GetAttributionRequest_FieldNumber_DeviceBrand = 16,
  GetAttributionRequest_FieldNumber_AdEventId = 17,
  GetAttributionRequest_FieldNumber_AcquisitionCampaign = 18,
  GetAttributionRequest_FieldNumber_DeviceId = 19,
};

GPB_FINAL @interface GetAttributionRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *advertiserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appUserId;

/** Attribution Source, appsflyer/adjust/branch etc */
@property(nonatomic, readwrite, copy, null_resettable) NSString *attributionSource;

/** Attribution Data, json string */
@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

/** Attribution Data, json string */
@property(nonatomic, readwrite, copy, null_resettable) NSString *networkUserId;

/** android, ios */
@property(nonatomic, readwrite, copy, null_resettable) NSString *os;

/** Operating system version: 6.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

/** App Package Name: com.some.app */
@property(nonatomic, readwrite, copy, null_resettable) NSString *packageName;

/** PackageInfo version name: 13.72.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *packageVersion;

/** Device Model Name: Google Pixel */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModel;

/** Device local: it_IT */
@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

/** Device timezone abbreviation: CEST */
@property(nonatomic, readwrite, copy, null_resettable) NSString *timeZoneAbv;

/** Device timezone: Europe/Rome */
@property(nonatomic, readwrite, copy, null_resettable) NSString *timeZone;

/** Carrier name: vodafone IT */
@property(nonatomic, readwrite, copy, null_resettable) NSString *carrier;

/** Device Brand : Google */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;

@property(nonatomic, readwrite, copy, null_resettable) NSString *adEventId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionCampaign;

/**
 * Our attribution data is from 3rd party platform and upload by developer.
 * So the advertiser_id could not assure it is not blank.
 * And the app_user_id can pass by developer, we could not use this as the unique id.
 * So we need SDK upload the device_id.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@end

#pragma mark - GetAttributionResponse

typedef GPB_ENUM(GetAttributionResponse_FieldNumber) {
  GetAttributionResponse_FieldNumber_AppId = 1,
  GetAttributionResponse_FieldNumber_AdvertiserId = 2,
  GetAttributionResponse_FieldNumber_AppUserId = 3,
  GetAttributionResponse_FieldNumber_AttributionSource = 4,
  GetAttributionResponse_FieldNumber_AcquisitionSource = 5,
  GetAttributionResponse_FieldNumber_AcquisitionCampaign = 6,
  GetAttributionResponse_FieldNumber_AcquisitionLander = 7,
  GetAttributionResponse_FieldNumber_AcquisitionCountry = 8,
  GetAttributionResponse_FieldNumber_AcquisitionVar1 = 9,
  GetAttributionResponse_FieldNumber_AcquisitionVar2 = 10,
  GetAttributionResponse_FieldNumber_AcquisitionVar3 = 11,
  GetAttributionResponse_FieldNumber_AdEventId = 12,
  GetAttributionResponse_FieldNumber_TrackerId = 13,
  GetAttributionResponse_FieldNumber_ClickTime = 14,
};

GPB_FINAL @interface GetAttributionResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *advertiserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *attributionSource;

@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionSource;

@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionCampaign;

@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionLander;

@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionCountry;

@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionVar1;

@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionVar2;

@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionVar3;

@property(nonatomic, readwrite, copy, null_resettable) NSString *adEventId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *trackerId;

@property(nonatomic, readwrite) int64_t clickTime;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
