// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

//#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
//#else
// #import "GPBProtocolBuffers.h"
//#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Event;
@class EventExtInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ErrCode

/**
 * start from 10000, grpc builtin code is less than 17.
 * uint32
 **/
typedef GPB_ENUM(ErrCode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ErrCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** there must be a zero value for proto3, and needs to be the first element for compatibility with the proto2 */
  ErrCode_Ok = 0,
};

GPBEnumDescriptor *ErrCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ErrCode_IsValidValue(int32_t value);

#pragma mark - EventRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EventRoot : GPBRootObject
@end

#pragma mark - EventExtInfo

typedef GPB_ENUM(EventExtInfo_FieldNumber) {
  EventExtInfo_FieldNumber_Os = 1,
  EventExtInfo_FieldNumber_OsVersion = 2,
  EventExtInfo_FieldNumber_PackageName = 3,
  EventExtInfo_FieldNumber_PackageVersion = 4,
  EventExtInfo_FieldNumber_DeviceModel = 5,
  EventExtInfo_FieldNumber_Locale = 6,
  EventExtInfo_FieldNumber_TimeZoneAbv = 7,
  EventExtInfo_FieldNumber_TimeZone = 8,
  EventExtInfo_FieldNumber_Carrier = 9,
  EventExtInfo_FieldNumber_ScreenWidth = 10,
  EventExtInfo_FieldNumber_ScreenHeight = 11,
  EventExtInfo_FieldNumber_ScreenDensity = 12,
  EventExtInfo_FieldNumber_ExtStorageSize = 13,
  EventExtInfo_FieldNumber_AvailableStorageSize = 14,
  EventExtInfo_FieldNumber_DeviceBrand = 15,
  EventExtInfo_FieldNumber_PackageVersionCode = 16,
};

@interface EventExtInfo : GPBMessage

/** android, ios */
@property(nonatomic, readwrite, copy, null_resettable) NSString *os;

/** Operating system version: 6.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

/** App Package Name: com.some.app */
@property(nonatomic, readwrite, copy, null_resettable) NSString *packageName;

/** PackageInfo version name: 13.72.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *packageVersion;

/** Device Model Name: Google Pixel */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModel;

/** Device local: it_IT */
@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

/** Device timezone abbreviation: CEST */
@property(nonatomic, readwrite, copy, null_resettable) NSString *timeZoneAbv;

/** Device timezone: Europe/Rome */
@property(nonatomic, readwrite, copy, null_resettable) NSString *timeZone;

/** Carrier name: vodafone IT */
@property(nonatomic, readwrite, copy, null_resettable) NSString *carrier;

/** Device screen width in pixels: 720 */
@property(nonatomic, readwrite) int32_t screenWidth;

/** Device screen height in pixels: 1208 */
@property(nonatomic, readwrite) int32_t screenHeight;

/** Device screen density: 2.00 */
@property(nonatomic, readwrite) double screenDensity;

/** An integer for the total external storage size in GB. */
@property(nonatomic, readwrite) int32_t extStorageSize;

/** An integer for the available external storage space in GB. */
@property(nonatomic, readwrite) int32_t availableStorageSize;

/** Device Brand : Google */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;

/** PackageInfo version code: 13 */
@property(nonatomic, readwrite) int32_t packageVersionCode;

@end

#pragma mark - Event

typedef GPB_ENUM(Event_FieldNumber) {
  Event_FieldNumber_Name = 1,
  Event_FieldNumber_Value = 2,
  Event_FieldNumber_Param = 13,
};

@interface Event : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

/** json string, limit 1024 bytes */
@property(nonatomic, readwrite, copy, null_resettable) NSString *param;

@end

#pragma mark - EventRequest

typedef GPB_ENUM(EventRequest_FieldNumber) {
  EventRequest_FieldNumber_Timestamp = 1,
  EventRequest_FieldNumber_AdvertiserId = 2,
  EventRequest_FieldNumber_AppUserId = 3,
  EventRequest_FieldNumber_ExtInfo = 4,
  EventRequest_FieldNumber_Event = 5,
  EventRequest_FieldNumber_DeviceId = 6,
  EventRequest_FieldNumber_SessionId = 7,
  EventRequest_FieldNumber_AcquisitionSource = 8,
  EventRequest_FieldNumber_Sdkversion = 9,
  EventRequest_FieldNumber_AcquisitionCampaign = 10,
};

@interface EventRequest : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

/** Apple's Advertising Identifier (IDFA) or Google's Android’s advertising ID. See how Facebook fetches this on iOS or on Android.  1111-1111-1111-1111 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *advertiserId;

/** Optional. String, up to 100 chars. See userID properties for more information. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appUserId;

/** Information about the device. This parameter must be in a specific format. */
@property(nonatomic, readwrite, strong, null_resettable) EventExtInfo *extInfo;
/** Test to see if @c extInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtInfo;

@property(nonatomic, readwrite, strong, null_resettable) Event *event;
/** Test to see if @c event has been set. */
@property(nonatomic, readwrite) BOOL hasEvent;

/** device id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

/** session */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** acquisition source: facebook/obix/adwords */
@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionSource;

/** sdk version: 0.1.1 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkversion;

/** acquisition campaign */
@property(nonatomic, readwrite, copy, null_resettable) NSString *acquisitionCampaign;

@end

#pragma mark - EventResponse

typedef GPB_ENUM(EventResponse_FieldNumber) {
  EventResponse_FieldNumber_Status = 1,
};

@interface EventResponse : GPBMessage

@property(nonatomic, readwrite) BOOL status;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
