// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: notification.proto

#import <Foundation/Foundation.h>

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#import "Notification.pbobjc.h"
#endif

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import <ProtoRPC/ProtoService.h>
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriteable.h>
#import <RxLibrary/GRXWriter.h>
#endif

@class UploadDeviceTokenRequest;
@class UploadDeviceTokenResponse;

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#endif

@class GRPCUnaryProtoCall;
@class GRPCStreamingProtoCall;
@class GRPCCallOptions;
@protocol GRPCProtoResponseHandler;
@class GRPCProtoCall;


NS_ASSUME_NONNULL_BEGIN

@protocol PushNotificationService2 <NSObject>

#pragma mark UploadDeviceToken(UploadDeviceTokenRequest) returns (UploadDeviceTokenResponse)

/**
 * UploadDeviceToken can be called by app, it should be called with metadata 'Authorization'
 */
- (GRPCUnaryProtoCall *)uploadDeviceTokenWithMessage:(UploadDeviceTokenRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

@end

/**
 * The methods in this protocol belong to a set of old APIs that have been deprecated. They do not
 * recognize call options provided in the initializer. Using the v2 protocol is recommended.
 */
@protocol PushNotificationService <NSObject>

#pragma mark UploadDeviceToken(UploadDeviceTokenRequest) returns (UploadDeviceTokenResponse)

/**
 * UploadDeviceToken can be called by app, it should be called with metadata 'Authorization'
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)uploadDeviceTokenWithRequest:(UploadDeviceTokenRequest *)request handler:(void(^)(UploadDeviceTokenResponse *_Nullable response, NSError *_Nullable error))handler;

/**
 * UploadDeviceToken can be called by app, it should be called with metadata 'Authorization'
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToUploadDeviceTokenWithRequest:(UploadDeviceTokenRequest *)request handler:(void(^)(UploadDeviceTokenResponse *_Nullable response, NSError *_Nullable error))handler;


@end


#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
/**
 * Basic service implementation, over gRPC, that only does
 * marshalling and parsing.
 */
@interface PushNotificationService : GRPCProtoService<PushNotificationService2, PushNotificationService>
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions NS_DESIGNATED_INITIALIZER;
+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions;
// The following methods belong to a set of old APIs that have been deprecated.
- (instancetype)initWithHost:(NSString *)host;
+ (instancetype)serviceWithHost:(NSString *)host;
@end
#endif

NS_ASSUME_NONNULL_END

