// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

//#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
//#else
// #import "GPBProtocolBuffers.h"
//#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NotificationRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface NotificationRoot : GPBRootObject
@end

#pragma mark - UploadDeviceTokenRequest

typedef GPB_ENUM(UploadDeviceTokenRequest_FieldNumber) {
  UploadDeviceTokenRequest_FieldNumber_DeviceId = 1,
  UploadDeviceTokenRequest_FieldNumber_DeviceToken = 2,
};

GPB_FINAL @interface UploadDeviceTokenRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceToken;

@end

#pragma mark - UploadDeviceTokenResponse

GPB_FINAL @interface UploadDeviceTokenResponse : GPBMessage

@end

#pragma mark - InAppMessage

typedef GPB_ENUM(InAppMessage_FieldNumber) {
  InAppMessage_FieldNumber_Id_p = 1,
  InAppMessage_FieldNumber_Title = 2,
  InAppMessage_FieldNumber_Content = 3,
  InAppMessage_FieldNumber_Html = 4,
};

GPB_FINAL @interface InAppMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *html;

@end

#pragma mark - GetInAppMessageRequest

typedef GPB_ENUM(GetInAppMessageRequest_FieldNumber) {
  GetInAppMessageRequest_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface GetInAppMessageRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
