// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: notification.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 40311
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 40311 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class InAppMessageContent;
@class Notification;
@class NotificationContent;
@class NotificationGroupByStatus;
@class NotificationLog;
@class NotificationSetting;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum TriggerType

typedef GPB_ENUM(TriggerType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  TriggerType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  TriggerType_TriggerTypeUnspecified = 0,
  TriggerType_TriggerTypeOnEvent = 1,
  TriggerType_TriggerTypeOnTime = 2,
  TriggerType_TriggerTypeOnSchedule = 3,
};

GPBEnumDescriptor *TriggerType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL TriggerType_IsValidValue(int32_t value);

#pragma mark - Enum NotificationStatus

typedef GPB_ENUM(NotificationStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NotificationStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NotificationStatus_NotificationStatusUnspecified = 0,
  NotificationStatus_NotificationStatusDraft = 1,
  NotificationStatus_NotificationStatusPending = 2,
  NotificationStatus_NotificationStatusRunning = 3,
  NotificationStatus_NotificationStatusPaused = 4,
  NotificationStatus_NotificationStatusFinish = 5,
};

GPBEnumDescriptor *NotificationStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NotificationStatus_IsValidValue(int32_t value);

#pragma mark - Enum AlertType

typedef GPB_ENUM(AlertType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  AlertType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  AlertType_AlertTypeUnspecified = 0,
  AlertType_AlertTypePushNotification = 1,
  AlertType_AlertTypeInApp = 2,
};

GPBEnumDescriptor *AlertType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AlertType_IsValidValue(int32_t value);

#pragma mark - Enum NotificationLogStatus

typedef GPB_ENUM(NotificationLogStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NotificationLogStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NotificationLogStatus_NotificationLogStatusUnspecified = 0,
  NotificationLogStatus_NotificationLogStatusPending = 1,
  NotificationLogStatus_NotificationLogStatusSuccess = 2,
  NotificationLogStatus_NotificationLogStatusFail = 3,
};

GPBEnumDescriptor *NotificationLogStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NotificationLogStatus_IsValidValue(int32_t value);

#pragma mark - NotificationRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface NotificationRoot : GPBRootObject
@end

#pragma mark - NotificationSetting

typedef GPB_ENUM(NotificationSetting_FieldNumber) {
  NotificationSetting_FieldNumber_TriggerType = 1,
  NotificationSetting_FieldNumber_NextTriggerAt = 2,
  NotificationSetting_FieldNumber_BeginAt = 3,
  NotificationSetting_FieldNumber_EndAt = 4,
  NotificationSetting_FieldNumber_SegmentId = 5,
  NotificationSetting_FieldNumber_Event = 6,
  NotificationSetting_FieldNumber_Cron = 7,
  NotificationSetting_FieldNumber_GroupTagId = 8,
  NotificationSetting_FieldNumber_FollowUpEventsArray = 9,
  NotificationSetting_FieldNumber_AbRatio = 10,
};

GPB_FINAL @interface NotificationSetting : GPBMessage

@property(nonatomic, readwrite) TriggerType triggerType;

/**
 * next_trigger_at is for next trigger time of the notification,
 * it is a clear time that the notification next run
 **/
@property(nonatomic, readwrite) int64_t nextTriggerAt;

@property(nonatomic, readwrite) int64_t beginAt;

@property(nonatomic, readwrite) int64_t endAt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *segmentId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *event;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cron;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupTagId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *followUpEventsArray;
/** The number of items in @c followUpEventsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger followUpEventsArray_Count;

@property(nonatomic, readwrite) float abRatio;

@end

/**
 * Fetches the raw value of a @c NotificationSetting's @c triggerType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NotificationSetting_TriggerType_RawValue(NotificationSetting *message);
/**
 * Sets the raw value of an @c NotificationSetting's @c triggerType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNotificationSetting_TriggerType_RawValue(NotificationSetting *message, int32_t value);

#pragma mark - NotificationContent

typedef GPB_ENUM(NotificationContent_FieldNumber) {
  NotificationContent_FieldNumber_Title = 1,
  NotificationContent_FieldNumber_Content = 2,
  NotificationContent_FieldNumber_ImageURL = 3,
};

GPB_FINAL @interface NotificationContent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imageURL;

@end

#pragma mark - InAppMessageContent

typedef GPB_ENUM(InAppMessageContent_FieldNumber) {
  InAppMessageContent_FieldNumber_Html = 1,
  InAppMessageContent_FieldNumber_Data_p = 2,
};

GPB_FINAL @interface InAppMessageContent : GPBMessage

/**
 * for in-app message
 * https://3.basecamp.com/5080746/buckets/22187245/todos/4606870414
 * html: the html content for visual constructor of in-app message
 * Example:
 * <html lang="en">
 * 		<head>
 * 			<meta charset="UTF-8" />
 * 			<meta http-equiv="X-UA-Compatible" content="IE=edge" />
 * 			<meta name="viewport" content="width=device-width, initial-scale=1.0" />
 * 			<title>Document</title>
 * 			<link rel="preconnect" href="https://fonts.googleapis.com" />
 * 			<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
 * 			<link
 * 				href="https://fonts.googleapis.com/css2?family=Montserrat:wght\@500;600&display=swap"
 * 				rel="stylesheet"
 * 			/>
 * 		</head>
 * ...
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *html;

/**
 * data: the data struct of visual constructor for web
 * Example:
 * {
 *  "backgroundColor": "",
 *  "header": {
 *    "data": "xxxxxx",
 *    "color": "#191919",
 *    "fontSize": "small",
 *    "fontAlign": "left"
 *   }
 * }
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@end

#pragma mark - InAppMessage

typedef GPB_ENUM(InAppMessage_FieldNumber) {
  InAppMessage_FieldNumber_Id_p = 1,
  InAppMessage_FieldNumber_Title = 2,
  InAppMessage_FieldNumber_Content = 3,
  InAppMessage_FieldNumber_Html = 4,
};

GPB_FINAL @interface InAppMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *html;

@end

#pragma mark - Notification

typedef GPB_ENUM(Notification_FieldNumber) {
  Notification_FieldNumber_Id_p = 1,
  Notification_FieldNumber_AppId = 2,
  Notification_FieldNumber_Name = 3,
  Notification_FieldNumber_Os = 4,
  Notification_FieldNumber_Setting = 5,
  Notification_FieldNumber_Content = 6,
  Notification_FieldNumber_Status = 7,
  Notification_FieldNumber_Vid = 8,
  Notification_FieldNumber_AlertType = 9,
  Notification_FieldNumber_InAppMessageContent = 10,
  Notification_FieldNumber_ContentB = 11,
};

GPB_FINAL @interface Notification : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** app_id is refer to App, ListNotifications api supports using app.name in order_by and filter */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *os;

@property(nonatomic, readwrite, strong, null_resettable) NotificationSetting *setting;
/** Test to see if @c setting has been set. */
@property(nonatomic, readwrite) BOOL hasSetting;

@property(nonatomic, readwrite, strong, null_resettable) NotificationContent *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite) NotificationStatus status;

/**
 * vid will change with every modification of notification
 * it is use in the delay task
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *vid;

@property(nonatomic, readwrite) AlertType alertType;

@property(nonatomic, readwrite, strong, null_resettable) InAppMessageContent *inAppMessageContent;
/** Test to see if @c inAppMessageContent has been set. */
@property(nonatomic, readwrite) BOOL hasInAppMessageContent;

@property(nonatomic, readwrite, strong, null_resettable) NotificationContent *contentB;
/** Test to see if @c contentB has been set. */
@property(nonatomic, readwrite) BOOL hasContentB;

@end

/**
 * Fetches the raw value of a @c Notification's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Notification_Status_RawValue(Notification *message);
/**
 * Sets the raw value of an @c Notification's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNotification_Status_RawValue(Notification *message, int32_t value);

/**
 * Fetches the raw value of a @c Notification's @c alertType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Notification_AlertType_RawValue(Notification *message);
/**
 * Sets the raw value of an @c Notification's @c alertType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNotification_AlertType_RawValue(Notification *message, int32_t value);

#pragma mark - CreateNotificationRequest

typedef GPB_ENUM(CreateNotificationRequest_FieldNumber) {
  CreateNotificationRequest_FieldNumber_Notification = 1,
};

GPB_FINAL @interface CreateNotificationRequest : GPBMessage

/**
 * it just needs to provider the fields: app_id, name, os, setting, content, alert_type
 * the fields trigger_at, event and cron is one and only one
 * when trigger_type is ON_EVENT, it needs the field event, which is specifies the trigger event
 * when trigger_type is ON_TIME, it needs the field cron, which is specifies the regular time
 * when trigger_type is ON_SCHEDULE, it needs the field trigger_at, which is specifies the trigger time
 **/
@property(nonatomic, readwrite, strong, null_resettable) Notification *notification;
/** Test to see if @c notification has been set. */
@property(nonatomic, readwrite) BOOL hasNotification;

@end

#pragma mark - UpdateNotificationRequest

typedef GPB_ENUM(UpdateNotificationRequest_FieldNumber) {
  UpdateNotificationRequest_FieldNumber_Notification = 1,
  UpdateNotificationRequest_FieldNumber_FieldMasksArray = 2,
};

GPB_FINAL @interface UpdateNotificationRequest : GPBMessage

/**
 * it can only update when status is "DRAFT" or "PENDING"
 * the field id, project_id and status could not be updated
 **/
@property(nonatomic, readwrite, strong, null_resettable) Notification *notification;
/** Test to see if @c notification has been set. */
@property(nonatomic, readwrite) BOOL hasNotification;

/** it can specifies the fields which is wanted be update. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *fieldMasksArray;
/** The number of items in @c fieldMasksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger fieldMasksArray_Count;

@end

#pragma mark - GetNotificationRequest

typedef GPB_ENUM(GetNotificationRequest_FieldNumber) {
  GetNotificationRequest_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface GetNotificationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - ListNotificationsRequest

typedef GPB_ENUM(ListNotificationsRequest_FieldNumber) {
  ListNotificationsRequest_FieldNumber_Limit = 1,
  ListNotificationsRequest_FieldNumber_Offset = 2,
  ListNotificationsRequest_FieldNumber_Filter = 3,
  ListNotificationsRequest_FieldNumber_OrderBy = 4,
};

GPB_FINAL @interface ListNotificationsRequest : GPBMessage

@property(nonatomic, readwrite) int32_t limit;

@property(nonatomic, readwrite) int32_t offset;

@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderBy;

@end

#pragma mark - ListNotificationsResponse

typedef GPB_ENUM(ListNotificationsResponse_FieldNumber) {
  ListNotificationsResponse_FieldNumber_NotificationsArray = 1,
  ListNotificationsResponse_FieldNumber_TotalSize = 2,
};

GPB_FINAL @interface ListNotificationsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Notification*> *notificationsArray;
/** The number of items in @c notificationsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger notificationsArray_Count;

@property(nonatomic, readwrite) int64_t totalSize;

@end

#pragma mark - StopNotificationRequest

typedef GPB_ENUM(StopNotificationRequest_FieldNumber) {
  StopNotificationRequest_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface StopNotificationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - StopNotificationResponse

GPB_FINAL @interface StopNotificationResponse : GPBMessage

@end

#pragma mark - PauseNotificationRequest

typedef GPB_ENUM(PauseNotificationRequest_FieldNumber) {
  PauseNotificationRequest_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface PauseNotificationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - PauseNotificationResponse

GPB_FINAL @interface PauseNotificationResponse : GPBMessage

@end

#pragma mark - RestartNotificationRequest

typedef GPB_ENUM(RestartNotificationRequest_FieldNumber) {
  RestartNotificationRequest_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface RestartNotificationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - RestartNotificationResponse

GPB_FINAL @interface RestartNotificationResponse : GPBMessage

@end

#pragma mark - DeleteNotificationRequest

typedef GPB_ENUM(DeleteNotificationRequest_FieldNumber) {
  DeleteNotificationRequest_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface DeleteNotificationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - PublishNotificationRequest

typedef GPB_ENUM(PublishNotificationRequest_FieldNumber) {
  PublishNotificationRequest_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface PublishNotificationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - PublishNotificationResponse

GPB_FINAL @interface PublishNotificationResponse : GPBMessage

@end

#pragma mark - UploadDeviceTokenRequest

typedef GPB_ENUM(UploadDeviceTokenRequest_FieldNumber) {
  UploadDeviceTokenRequest_FieldNumber_DeviceId = 1,
  UploadDeviceTokenRequest_FieldNumber_DeviceToken = 2,
};

GPB_FINAL @interface UploadDeviceTokenRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceToken;

@end

#pragma mark - UploadDeviceTokenResponse

GPB_FINAL @interface UploadDeviceTokenResponse : GPBMessage

@end

#pragma mark - GetInAppMessageRequest

typedef GPB_ENUM(GetInAppMessageRequest_FieldNumber) {
  GetInAppMessageRequest_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface GetInAppMessageRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - StartNotificationByVidRequest

typedef GPB_ENUM(StartNotificationByVidRequest_FieldNumber) {
  StartNotificationByVidRequest_FieldNumber_Vid = 1,
};

GPB_FINAL @interface StartNotificationByVidRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *vid;

@end

#pragma mark - StartNotificationByVidResponse

GPB_FINAL @interface StartNotificationByVidResponse : GPBMessage

@end

#pragma mark - SendNotificationRequest

typedef GPB_ENUM(SendNotificationRequest_FieldNumber) {
  SendNotificationRequest_FieldNumber_Vid = 1,
  SendNotificationRequest_FieldNumber_DeviceIdsArray = 2,
  SendNotificationRequest_FieldNumber_TemplateData = 3,
};

GPB_FINAL @interface SendNotificationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *vid;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *deviceIdsArray;
/** The number of items in @c deviceIdsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger deviceIdsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *templateData;

@end

#pragma mark - SendNotificationResponse

GPB_FINAL @interface SendNotificationResponse : GPBMessage

@end

#pragma mark - BatchSendNotificationRequest

typedef GPB_ENUM(BatchSendNotificationRequest_FieldNumber) {
  BatchSendNotificationRequest_FieldNumber_Vid = 1,
  BatchSendNotificationRequest_FieldNumber_Offset = 2,
  BatchSendNotificationRequest_FieldNumber_Limit = 3,
};

GPB_FINAL @interface BatchSendNotificationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *vid;

@property(nonatomic, readwrite) int32_t offset;

@property(nonatomic, readwrite) int32_t limit;

@end

#pragma mark - BatchSendNotificationResponse

typedef GPB_ENUM(BatchSendNotificationResponse_FieldNumber) {
  BatchSendNotificationResponse_FieldNumber_SendTotal = 1,
  BatchSendNotificationResponse_FieldNumber_SendSuccess = 2,
};

GPB_FINAL @interface BatchSendNotificationResponse : GPBMessage

/** send_total is the all selected users, may include those already sent */
@property(nonatomic, readwrite) int32_t sendTotal;

@property(nonatomic, readwrite) int32_t sendSuccess;

@end

#pragma mark - RunNotificationByVidRequest

typedef GPB_ENUM(RunNotificationByVidRequest_FieldNumber) {
  RunNotificationByVidRequest_FieldNumber_Vid = 1,
};

GPB_FINAL @interface RunNotificationByVidRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *vid;

@end

#pragma mark - RunNotificationByVidResponse

GPB_FINAL @interface RunNotificationByVidResponse : GPBMessage

@end

#pragma mark - NotificationGroupByStatus

typedef GPB_ENUM(NotificationGroupByStatus_FieldNumber) {
  NotificationGroupByStatus_FieldNumber_Status = 1,
  NotificationGroupByStatus_FieldNumber_Count = 2,
};

GPB_FINAL @interface NotificationGroupByStatus : GPBMessage

@property(nonatomic, readwrite) NotificationStatus status;

@property(nonatomic, readwrite) int32_t count;

@end

/**
 * Fetches the raw value of a @c NotificationGroupByStatus's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NotificationGroupByStatus_Status_RawValue(NotificationGroupByStatus *message);
/**
 * Sets the raw value of an @c NotificationGroupByStatus's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNotificationGroupByStatus_Status_RawValue(NotificationGroupByStatus *message, int32_t value);

#pragma mark - CountNotificationsGroupByStatusRequest

typedef GPB_ENUM(CountNotificationsGroupByStatusRequest_FieldNumber) {
  CountNotificationsGroupByStatusRequest_FieldNumber_Filter = 1,
};

GPB_FINAL @interface CountNotificationsGroupByStatusRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

@end

#pragma mark - CountNotificationsGroupByStatusResponse

typedef GPB_ENUM(CountNotificationsGroupByStatusResponse_FieldNumber) {
  CountNotificationsGroupByStatusResponse_FieldNumber_DataArray = 1,
};

GPB_FINAL @interface CountNotificationsGroupByStatusResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NotificationGroupByStatus*> *dataArray;
/** The number of items in @c dataArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dataArray_Count;

@end

#pragma mark - NotificationLog

typedef GPB_ENUM(NotificationLog_FieldNumber) {
  NotificationLog_FieldNumber_Id_p = 1,
  NotificationLog_FieldNumber_NotificationId = 2,
  NotificationLog_FieldNumber_DeviceId = 3,
  NotificationLog_FieldNumber_NotificationAt = 4,
  NotificationLog_FieldNumber_Status = 5,
  NotificationLog_FieldNumber_AppUserId = 6,
};

GPB_FINAL @interface NotificationLog : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *notificationId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite) int64_t notificationAt;

@property(nonatomic, readwrite) NotificationLogStatus status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appUserId;

@end

/**
 * Fetches the raw value of a @c NotificationLog's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NotificationLog_Status_RawValue(NotificationLog *message);
/**
 * Sets the raw value of an @c NotificationLog's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNotificationLog_Status_RawValue(NotificationLog *message, int32_t value);

#pragma mark - ListNotificationLogsRequest

typedef GPB_ENUM(ListNotificationLogsRequest_FieldNumber) {
  ListNotificationLogsRequest_FieldNumber_Limit = 1,
  ListNotificationLogsRequest_FieldNumber_Offset = 2,
  ListNotificationLogsRequest_FieldNumber_Filter = 3,
  ListNotificationLogsRequest_FieldNumber_OrderBy = 4,
};

GPB_FINAL @interface ListNotificationLogsRequest : GPBMessage

@property(nonatomic, readwrite) int32_t limit;

@property(nonatomic, readwrite) int32_t offset;

@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderBy;

@end

#pragma mark - ListNotificationLogsResponse

typedef GPB_ENUM(ListNotificationLogsResponse_FieldNumber) {
  ListNotificationLogsResponse_FieldNumber_NotificationLogsArray = 1,
  ListNotificationLogsResponse_FieldNumber_TotalSize = 2,
};

GPB_FINAL @interface ListNotificationLogsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NotificationLog*> *notificationLogsArray;
/** The number of items in @c notificationLogsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger notificationLogsArray_Count;

@property(nonatomic, readwrite) int64_t totalSize;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
